CREATE TABLE SYMBOL (
  	NAME VARCHAR(100) PRIMARY KEY
);

CREATE TABLE ACCOUNT ( 
	ACCOUNT_ID SERIAL PRIMARY KEY,
	BALANCE MONEY NOT NULL DEFAULT 0
);

CREATE TABLE POSITION (
	POSITION_ID SERIAL PRIMARY KEY,
	ACCOUNT_ID INT NOT NULL,
  	SYMBOL_NAME INT NOT NULL,
  	AMOUNT DOUBLE NOT NULL DEFAULT 0,
	FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID) ON DELETE CASCADE,
  	FOREIGN KEY (SYMBOL_NAME) REFERENCES SYMBOL(NAME) ON DELETE CASCADE
);

CREATE TABLE ORDER ( 
	ID SERIAL PRIMARY KEY,
	ORDER_ID SERIAL NOT NULL,
	ACCOUNT_ID INT NOT NULL,
	STATUS VARCHAR(100) NOT NULL,
	SYMBOL_ID INT NOT NULL,
	AMOUNT DOUBLE NOT NULL,
	PRICE MONEY NOT NULL,
	CREATE_AT TIMESTAMPTZ NOT NULL DEFAULT now()
	FOREIGN KEY (SYMBOL_ID) REFERENCES SYMBOL(SYMBOL_ID) ON DELETE CASCADE,
	FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID) ON DELETE CASCADE,
);