CREATE TABLE SYMBOL (
  	NAME TEXT PRIMARY KEY
);

CREATE TABLE ACCOUNT ( 
	ACCOUNT_ID INT PRIMARY KEY,
	BALANCE MONEY NOT NULL DEFAULT 0
);

CREATE TABLE POSITION (
	POSITION_ID SERIAL PRIMARY KEY,
	ACCOUNT_ID INT NOT NULL,
  SYMBOL TEXT NOT NULL,
  AMOUNT FLOAT NOT NULL DEFAULT 0,
	FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID) ON DELETE CASCADE,
  FOREIGN KEY (SYMBOL) REFERENCES SYMBOL(NAME) ON DELETE CASCADE
);

CREATE TABLE SYM_ORDER ( 
	ID SERIAL PRIMARY KEY,
	ORDER_ID SERIAL NOT NULL,
	ACCOUNT_ID INT NOT NULL,
	STATUS VARCHAR(100) NOT NULL,
	SYMBOL TEXT NOT NULL,
	AMOUNT FLOAT NOT NULL,
	PRICE MONEY NOT NULL,
	CREATE_AT TIMESTAMPTZ NOT NULL DEFAULT now(),
	FOREIGN KEY (SYMBOL) REFERENCES SYMBOL(NAME) ON DELETE CASCADE,
	FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID) ON DELETE CASCADE
);
